---
title: "A website 👋"
subtitle: "This is a practice website to help you learn how to make a website (so meta)."
---

This practice website was created to use as teaching materials for Ohio State University's [Code Club](https://osu-codeclub.github.io/).

The basics steps for creating a website are:

# Initiate a Quarto website in RStudio

You can learn how to initiate a new Quarto website [here](https://osu-codeclub.github.io/posts/website_01_initiation/).

# Add new pages

You can learn how to add new pages [here](https://osu-codeclub.github.io/posts/website_02/#adding-a-new-page-to-your-site).

# Customize your YAML

You can learn how to customize your YAML [here](https://osu-codeclub.github.io/posts/website_02/#modifying-the-yaml-header-of-our-new-page).

# Deploy using GitHub

You can learn how to deploy your website using GitHub, GitHub Pages, and GitHub Desktop [here](https://osu-codeclub.github.io/posts/website_03_deploy-github/).

# Interact with your GitHub repo

You can learn how to change the URL for your website, add About and description on GitHub, and push your changes online, [here](https://osu-codeclub.github.io/posts/website_04/).

# Alter your website styling

You can learn how to make a fancy about page, add drop down headers, and change the styling of your site [here](https://osu-codeclub.github.io/posts/website_05/).

# Make a Quarto presentation

You can learn how to make a Quarto presentaation [here](https://osu-codeclub.github.io/posts/website_07_presentation/).